"use strict";
const $ = id => document.getElementById(id);
const fragment = new URLSearchParams(location.hash.slice(1));
if (fragment.get('token')) { sessionStorage.setItem('cell-token', fragment.get('token')); history.replaceState(null, '', '/'); }
let token = sessionStorage.getItem('cell-token') || '', snapshot = null, selected = null, polling = false, dialogAction = null;
let rendered = {}, toastTimer;
const statusNames = {running:'실행 중',paused:'일시정지',starting:'준비 중',report_ready:'보고 완료 · 검증 별도',failed:'실패',killed:'강제 종료',interrupted:'연결 중단',created:'준비',stopped:'중단'};
const kindNames = {cell_created:'세포 생성',start:'작업 시작',tool_requested:'도구 요청',tool_result:'도구 결과',budget:'사용량 갱신',final:'세포 보고',stopped:'세포 중단',started:'감독 프로세스 시작',worker_outcome:'작업자 결과',kill_probe:'중단 실험 프로세스',killed:'비상 정지 확인',approval_required:'명령 승인 대기',pause:'일시정지 요청',resume:'실행 재개'};
function node(tag, cls, text) { const n=document.createElement(tag); if(cls)n.className=cls; if(text!==undefined)n.textContent=text; return n; }
function toast(text, error=false) { const n=$('toast'); n.textContent=text; n.className=error?'error':''; n.hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>n.hidden=true,6500); }
async function api(path, data) { const response=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(path.startsWith("mesh-sync")?35000:8000)}); const result=await response.json(); if(!response.ok){if(response.status===401)$('auth-panel').hidden=false;throw new Error(result.error||'요청 실패');}return result; }
async function action(path,data={}) {try {const result=await api(path,data);await refresh();return result;}catch(error){toast(error.message,true);throw error;}}
function button(text, fn, disabled=false) {const b=node('button','button subtle',text);b.type='button';b.disabled=disabled;b.addEventListener('click',()=>Promise.resolve().then(fn).catch(()=>{}));return b;}
function empty(container,text){container.append(node('div','empty',text));}
function changed(key,data,render){const serialized=JSON.stringify(data);if(rendered[key]!==serialized){rendered[key]=serialized;render();}}
function review(title, description, fn, reset=false) {$('dialog-title').textContent=title;$('dialog-description').textContent=description;$('dialog-input').value='';$('dialog-input').placeholder=reset?'RESUME':'어떤 결과를 확인했는지 구체적으로 적어 주세요.';$('dialog-input').minLength=reset?6:5;dialogAction=fn;$('dialog').showModal();}
$('dialog-cancel').onclick=()=>$('dialog').close();
$('dialog-form').onsubmit=async e=>{e.preventDefault();try{await dialogAction($('dialog-input').value);$('dialog').close();toast('기록했습니다.');}catch(error){toast(error.message,true);}};
function drawNetwork(cells){const host=$('network');host.replaceChildren();if(!cells.length){const c=node('div','empty-network');c.append(node('div','empty-symbol','◉'),node('strong','','첫 세포가 시작을 기다립니다'),node('p','','목표를 주면 필요한 역할로 분화합니다.'));host.append(c);return;}
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 640 350');svg.setAttribute('role','img');svg.setAttribute('aria-label','세포의 부모 자식 관계');const levels=[[],[],[]], byId=new Map(cells.map(c=>[c.id,c]));
 for(const c of cells){let depth=0,p=c.parent,seen=new Set();while(p&&byId.has(p)&&depth<2&&!seen.has(p)){seen.add(p);depth++;p=byId.get(p).parent;}levels[depth].push(c);}
 const positions=new Map();levels.forEach((row,depth)=>row.forEach((c,i)=>positions.set(c.id,{x:(i+1)*640/(row.length+1),y:65+depth*105})));
 for(const c of cells){if(c.parent&&positions.has(c.parent)){const p=positions.get(c.parent),q=positions.get(c.id),line=document.createElementNS(ns,'line');line.setAttribute('x1',p.x);line.setAttribute('y1',p.y+23);line.setAttribute('x2',q.x);line.setAttribute('y2',q.y-23);svg.append(line);}}
 for(const c of cells){const p=positions.get(c.id),g=document.createElementNS(ns,'g');const rect=document.createElementNS(ns,'rect');rect.setAttribute('x',p.x-62);rect.setAttribute('y',p.y-26);rect.setAttribute('width',124);rect.setAttribute('height',59);rect.setAttribute('rx',9);rect.setAttribute('class','node-box '+(!c.parent?'node-root ':'')+(c.status==='stopped'?'node-stopped':c.status==='report_ready'?'node-done':''));g.append(rect);const t=document.createElementNS(ns,'text');t.setAttribute('x',p.x);t.setAttribute('y',p.y-3);t.textContent=c.role==='stem'?'줄기세포':c.role.slice(0,16);g.append(t);const sub=document.createElementNS(ns,'text');sub.setAttribute('x',p.x);sub.setAttribute('y',p.y+15);sub.setAttribute('class','node-label');sub.textContent=(statusNames[c.status]||c.status).slice(0,16);g.append(sub);const title=document.createElementNS(ns,'title');title.textContent=c.role+' · '+c.id+' · '+c.tool;g.append(title);svg.append(g);}host.append(svg);
}
function renderEvents(id, events){const host=$(id);host.replaceChildren();if(!events.length)return empty(host,'아직 기록된 활동이 없습니다.');for(const item of [...events].reverse()){const row=node('div','event'),detail=node('details');row.append(node('time','',new Date(item.at*1000).toLocaleTimeString('ko-KR',{hour12:false})),node('span','event-cell',item.cell.slice(0,8)));detail.append(node('summary','',kindNames[item.kind]||item.kind),node('pre','',item.detail));row.append(detail);host.append(row);}}
function renderRecords(data){
 changed('routes',[data.routes,!!data.active],()=>{const host=$('routes');host.replaceChildren();$('route-count').textContent=data.routes.length+' ROUTES';if(!data.routes.length)return empty(host,'탐색 경로가 아직 없습니다. 데모 또는 실제 조사 후 후보가 등록됩니다.');for(const r of data.routes){const card=node('article','record');card.append(node('h3','',r.name+' · '+(r.status==='active'?'사용자 확인됨':r.status==='needs_review'?'재검토 필요':'후보')),node('p','',r.problem));for(const [k,label] of [['locator','위치'],['strategy','찾는 방법'],['verification','검증'],['fallback','대체 경로']])card.append(node('p','',label+' · '+r[k]));card.append(node('p','record-meta',`관측 성공 ${r.successes} · 실패 ${r.failures} · ${r.stale?'최근 검증 필요':'30일 이내 검토'} · 관련 경로 ${(r.related||[]).join(', ')||'없음'}`));const actions=node('div','record-actions');for(const [v,label] of [['pass','성공 근거 기록'],['fail','실패 근거 기록']])actions.append(button(label,()=>review(label,r.problem,evidence=>action('route-review',{name:r.name,digest:r.digest,verdict:v,evidence,run:data.selected||''})),!!data.active));card.append(actions);host.append(card);}});
 changed('memories',data.memories,()=>{const host=$('memories');host.replaceChildren();if(!data.memories.length)return empty(host,'저장된 경험이 없습니다.');for(const m of data.memories){const c=node('article','record');c.append(node('h3','',m.topic),node('p','',m.content),node('p','record-meta','출처 · '+m.source+' / '+m.confidence+' (기록자의 주장)'));host.append(c);}});
 changed('skills',[data.skills,!!data.active],()=>{const host=$('skills');host.replaceChildren();if(!data.skills.length)return empty(host,'재사용 절차가 없습니다.');for(const s of data.skills){const c=node('article','record');c.append(node('h3','',s.name+' · '+(s.status==='active'?'활성':'후보')),node('p','',s.instructions),node('p','record-meta','근거 · '+s.evidence));if(s.status!=='active')c.append(button('근거 검토 후 활성화',()=>review('절차 활성화',s.instructions+'\n\n근거: '+s.evidence,async evidence=>{await action('skill-activate',{name:s.name,digest:s.digest,evidence});}),!!data.active));host.append(c);}});
 changed('changes',[data.changes,!!data.active],()=>{const host=$('changes');host.replaceChildren();if(!data.changes.length)return empty(host,'파일 도구의 변경 기록이 없습니다.');for(const c of data.changes){const item=node('div','record');item.append(node('code','',c.path),node('p','record-meta',new Date(c.at*1000).toLocaleString('ko-KR')));item.append(button('이 변경 되돌리기',()=>review('파일 변경 복구',c.path+'\n이후의 변경이 있으면 복구를 거부합니다.',()=>action('restore',{change_id:c.id})),!!data.active));host.append(item);}});
 changed('runs',[data.runs,data.evaluations,!!data.active],()=>{const host=$('run-list'),evalhost=$('evaluation-list');host.replaceChildren();evalhost.replaceChildren();if(!data.runs.length){empty(host,'실행 이력이 없습니다.');empty(evalhost,'완료한 작업을 실행한 후 결과를 평가할 수 있습니다.');}for(const r of data.runs){const c=node('article','record');c.append(node('h3','',r.goal),node('p','record-meta',(statusNames[r.status]||r.status)+' · '+r.config.mode+' · '+new Date(r.created*1000).toLocaleString('ko-KR')));c.append(button('이 실행 보기',()=>{selected=r.id;rendered={};return refresh();}));host.append(c);if(['report_ready','failed','killed','interrupted'].includes(r.status)){const ec=node('article','record'),ev=data.evaluations.find(e=>e.run===r.id);ec.append(node('h3','',r.goal),node('p','', '완료 기준 · '+r.criteria),node('p','record-meta',r.config.mode==='live'?'실제 API 작업': '고정 시나리오 · 지능 평가에서 제외'));if(ev)ec.append(node('p','',`사용자 평가: ${ev.verdict==='pass'?'통과':'실패'}\n${ev.evidence}`));const actions=node('div','record-actions');for(const [v,label] of [['pass','기준 충족'],['fail','기준 미충족']])actions.append(button(label,()=>review('작업 평가',r.criteria,evidence=>action('evaluate',{run:r.id,verdict:v,evidence})),!!data.active));ec.append(actions);evalhost.append(ec);}}if(!evalhost.children.length)empty(evalhost,'현재 실행이 끝나면 평가할 수 있습니다.');});
}
function render(data){snapshot=data;const current=data.runs.find(r=>r.id===data.selected),active=data.runs.find(r=>r.id===data.active);$('auth-panel').hidden=true;$('connection').textContent='로컬 제어 연결됨';$('conn-dot').className='dot';$('last-update').textContent=new Date().toLocaleTimeString('ko-KR',{hour12:false});
 $('state-pill').textContent=data.halted?'정지 잠금':active?(statusNames[active.status]||active.status):'대기';$('state-pill').className='pill'+(data.halted?' red':active?.status==='paused'?' yellow':'');$('state-summary').textContent=data.halted?'실행이 잠겼습니다. 새 작업은 시작되지 않습니다.':active?active.goal:'새로운 목표를 기다립니다';$('state-help').textContent=data.halted?'실행 결과와 변경 사항을 확인한 뒤 직접 잠금을 해제하세요.':active?.status==='paused'?'다음 도구·모델 호출 경계에서 대기합니다. 진행 중인 호출을 끝내려면 비상 정지를 사용하세요.':'비상 정지는 작업자와 작업 그룹의 하위 프로세스를 종료합니다.';
 $('pause').disabled=!data.active;$('pause').textContent=active?.status==='paused'?'계속 실행':'일시정지';$('reset').hidden=!data.halted;$('start').disabled=!!data.active||data.halted;$('kill-test').disabled=!!data.active||data.halted;$('compact').disabled=!!data.active;$('roots').textContent=data.roots.join('\n');
 $('metric-cells').replaceChildren(document.createTextNode(data.cells.filter(c=>c.status==='running').length+' '),node('small','','cells'));$('metric-total').textContent='생성된 하위 세포 '+data.metrics.cells+'개';$('metric-calls').replaceChildren(document.createTextNode(data.metrics.calls+' '),node('small','','calls'));$('metric-tokens').textContent=data.metrics.tokens.toLocaleString()+' tokens · 실행 전체 합산';$('metric-memory').replaceChildren(document.createTextNode((data.peak_bytes/1048576).toFixed(1)+' '),node('small','','MB'));$('metric-storage').replaceChildren(document.createTextNode((data.storage.state_bytes/1048576).toFixed(2)+' '),node('small','','MB'));$('metric-records').textContent=`기억 ${data.storage.memories} · 절차 ${data.storage.skills}`;
 $('network-label').textContent=current?current.config.mode.toUpperCase():'STANDBY';$('result').textContent=current?(current.result||current.reason||'작업이 진행 중입니다. 아래 활동 기록을 확인하세요.'):'작업 결과와 확인할 근거가 여기에 나타납니다.';
 changed('network',data.cells,()=>drawNetwork(data.cells));changed('events',data.events,()=>{renderEvents('activity-list',data.events.filter(e=>e.kind!=='budget').slice(-8));renderEvents('history-events',data.events);});
 changed('approvals',data.approvals,()=>{const host=$('approvals');host.replaceChildren();for(const a of data.approvals){const n=node('div','approval');n.append(node('h2','','명령 실행을 기다립니다'),node('pre','',JSON.parse(a.argv).join(' ')),node('p','',a.cwd));const actions=node('div','record-actions');actions.append(button('이 명령 실행',()=>action('approve',{id:a.id,allow:true})),button('거절',()=>action('approve',{id:a.id,allow:false})));n.append(actions);host.append(n);}});renderRecords(data);window.dispatchEvent(new CustomEvent("cell-snapshot",{detail:data}));
}
async function refresh(){if(polling||!token)return;polling=true;try{render(await api('snapshot?'+new URLSearchParams({...selected?{run:selected}:{},...window.cellChatId?{chat:window.cellChatId}:{}})));}catch(error){$('connection').textContent='연결 끊김 · 상태 미확인';$('conn-dot').className='dot stopped';$('start').disabled=true;$('kill-test').disabled=true;$('state-summary').textContent='제어 연결을 확인할 수 없습니다';$('state-help').textContent='종료되었다고 가정하지 마세요. 제어 서버와 연결 상태를 확인하세요.';}finally{polling=false;}}
$('connect').onclick=()=>{token=$('session-token').value.trim();sessionStorage.setItem('cell-token',token);$('session-token').value='';refresh();};
$('mode').onchange=()=>{const live=$('mode').value==='live';$('live-options').hidden=!live;$('demo-note').hidden=live;};
$('task-form').onsubmit=async e=>{e.preventDefault();const payload={mode:$('mode').value,goal:$('goal').value,criteria:$('criteria').value,shell:$('shell').value,api_key:$('api-key').value,web:$('web').checked};for(const [id,key] of [['max-calls','max_calls'],['max-cells','max_cells'],['seconds','seconds'],['tokens','tokens'],['memory-mb','memory_mb'],['cpu-percent','cpu_percent']])payload[key]=Number($(id).value);$('start').disabled=true;try{selected=null;await action('start',payload);toast('작업을 시작했습니다.');}catch{}finally{$('api-key').value='';}};
$('kill').onclick=async()=>{const b=$('kill');b.disabled=true;b.textContent='정지 요청 중…';try{await action('kill');toast('작업 종료를 확인했습니다. 새 실행도 잠겼습니다.');}catch{toast('종료 확인 실패. 제어 서버 상태를 직접 확인하세요.',true);}finally{b.disabled=false;b.textContent='■  비상 정지';}};
$('pause').onclick=()=>{const r=snapshot?.runs.find(r=>r.id===snapshot.active);action(r?.status==='paused'?'resume':'pause').catch(()=>{});};
$('reset').onclick=()=>review('비상 정지 잠금 해제','이전 작업은 자동으로 재개되지 않습니다. 새 실행을 허용하려면 RESUME을 입력하세요.',confirmation=>action('reset',{confirmation}),true);
$('kill-test').onclick=async()=>{selected=null;try{await action('start',{mode:'kill_test',goal:'킬 스위치 실험: 하위 프로세스 카운터 중단',criteria:'비상 정지 후 카운터 파일이 더 이상 변경되지 않아야 한다.',seconds:120});}catch{}};
$('compact').onclick=()=>action('compact').then(r=>toast(`${r.archived_events}개 이벤트를 압축했습니다. 백업은 보존됩니다.`)).catch(()=>{});
for(const tab of document.querySelectorAll('[data-view]'))tab.onclick=()=>{document.body.classList.toggle('chat-view',tab.dataset.view==='chat');for(const n of document.querySelectorAll('[data-view]'))n.classList.toggle('active',n===tab);for(const n of document.querySelectorAll('.view'))n.hidden=n.id!=='view-'+tab.dataset.view;$('page-title').textContent={chat:'함께 만드는 작업 공간',mesh:'연결과 공유',overview:'세포 관제실',memory:'기억과 탐색 경로',growth:'성장 평가',history:'실행 기록'}[tab.dataset.view];};
if(!token)$('auth-panel').hidden=false;drawNetwork([]);refresh();setInterval(refresh,1000);
