"use strict";
let chatId=null, attachments=[];
const navChat=document.querySelector('[data-view="chat"]');
function openChat(id){chatId=id;window.cellChatId=id;selected=null;navChat.click();refresh();}
$('new-chat').onclick=async()=>{try{const r=await api('chat-new',{});openChat(r.chat);}catch(e){toast(e.message,true);}};
$('chat-form').onsubmit=async e=>{e.preventDefault();const message=$('chat-input').value.trim();if(!message)return;$('chat-send').disabled=true;try{if(!chatId){const c=await api('chat-new',{});chatId=c.chat;window.cellChatId=chatId;}const r=await api('chat-send',{chat:chatId,message:message+(attachments.length?'\n\n첨부 파일 경로 (read_file로 확인):\n'+attachments.map(a=>a.path).join('\n'):''),mode:$('chat-mode').value,shell:'ask',web:$('chat-web').checked});selected=r.run;$('chat-input').value='';attachments=[];showAttachments();await refresh();}catch(error){toast(error.message,true);$('chat-send').disabled=false;}};
$('chat-input').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){$('chat-form').requestSubmit();}};
$('save-key').onclick=async()=>{try{await action('configure-key',{api_key:$('chat-key').value});$('chat-key').value='';toast('키 설정을 반영했습니다. 서버를 닫으면 지워집니다.');}catch{}};
$('clear-key').onclick=()=>action('configure-key',{api_key:''}).catch(()=>{});
$('chat-mode').onchange=()=>{$('chat-demo-note').hidden=$('chat-mode').value!=='demo';};
function showAttachments(){$('chat-attachments').replaceChildren();for(const a of attachments)$('chat-attachments').append(button('첨부: '+a.name+' ×',()=>{attachments=attachments.filter(x=>x!==a);showAttachments();}));}
$('chat-file').onchange=async e=>{try{for(const file of e.target.files){if(file.size>40000)throw Error('텍스트 파일당 40 KB까지 지원합니다.');if(attachments.length>=4)throw Error('한 메시지에 최대 4개 파일을 첨부할 수 있습니다.');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());attachments.push(await api('upload',{name:file.name,text}));}showAttachments();}catch(error){toast(error.message,true);}finally{e.target.value='';}};
for(const b of document.querySelectorAll('[data-prompt]'))b.onclick=()=>{$('chat-input').value=b.dataset.prompt;$('chat-input').focus();};
function renderChat(data){const c=data.conversation;if(!c)return;if(!chatId&&c.chat){chatId=c.chat;window.cellChatId=chatId;}changed('chat-list',[c.chats,chatId],()=>{const host=$('conversation-list');host.replaceChildren();for(const x of c.chats){const b=button(x.title,()=>openChat(x.id));b.className='conversation-link'+(x.id===chatId?' current':'');host.append(b);}});
 changed('chat-messages',c.messages,()=>{const host=$('chat-messages');const near=host.scrollHeight-host.scrollTop-host.clientHeight<150;host.replaceChildren();$('chat-welcome').hidden=!!c.messages.length;for(const m of c.messages){const row=node('article','chat-message '+m.role);row.append(node('div','message-author',m.role==='user'?'YOU':'◉ CELL'),node('pre','message-content',m.content));if(m.role==='assistant'){row.append(node('span','record-meta',statusNames[m.status]||m.status));row.append(button('작업 기록 보기',()=>{selected=m.run;document.querySelector('[data-view="overview"]').click();refresh();}));}host.append(row);}if(near)host.scrollTop=host.scrollHeight;});
 $('chat-send').disabled=!!data.active||data.halted;$('chat-file').disabled=!!data.active;$('key-status').textContent=data.key_configured?'API 키 연결됨 · 서버 메모리에만 보관':'실제 대화를 시작하려면 API 키를 설정하세요';
 changed('chat-approvals',data.approvals,()=>{const h=$('chat-approvals');h.replaceChildren();for(const a of data.approvals){const n=node('div','approval');n.append(node('strong','','명령 실행 승인'),node('pre','',JSON.parse(a.argv).join(' ')),node('p','',a.cwd),button('실행 허용',()=>action('approve',{id:a.id,allow:true})),button('거절',()=>action('approve',{id:a.id,allow:false})));h.append(n);}});
 const active=data.runs.find(r=>r.id===data.active);const event=data.events.filter(e=>['tool_requested','cell_created','approval_required'].includes(e.kind)).at(-1);$('chat-progress').textContent=active?(statusNames[active.status]+' · '+(event?(kindNames[event.kind]||event.kind):'준비 중')):data.halted?'상단에서 정지 잠금을 해제하면 새 대화를 시작할 수 있습니다.':'메시지와 첨부한 파일의 내용은 실제 실행 시 모델 API로 전달될 수 있습니다.';
 renderMesh(data);
}
function renderMesh(data){const m=data.mesh;if(!m)return;$('mesh-available').textContent=m.available?'서명된 탐색 절차를 선택해 공유합니다. 받은 절차는 자동 실행되지 않습니다.':m.reason||'공유 모듈 사용 불가';if(!m.available)return;$('mesh-public').textContent=m.public;$('mesh-fingerprint').textContent=m.fingerprint;
 changed('mesh-peers',m.peers,()=>{const h=$('mesh-peers');h.replaceChildren();if(!m.peers.length)empty(h,'아직 연결한 컴퓨터가 없습니다. 상대의 HTTPS 피드 주소와 공개 키를 등록하세요.');for(const p of m.peers){const c=node('article','record');c.append(node('h3','',p.url),node('p','record-meta','지문 '+p.id),node('p','',p.enabled?'연결 허용 · 버전 '+p.sequence:'연결 차단됨'));if(p.enabled)c.append(button('가져오기 / 손상 복원',async()=>{const r=await api('mesh-sync',{peer:p.id});toast(`새 패키지 ${r.received} · 복원 ${r.repaired} · 남음 ${r.remaining}`);refresh();}),button('연결 차단',()=>action('mesh-disable',{peer:p.id})));h.append(c);}});
 changed('mesh-packages',m.packages,()=>{const h=$('mesh-packages');h.replaceChildren();if(!m.packages.length)empty(h,'받은 패키지가 없습니다.');for(const p of m.packages){const c=node('article','record');c.append(node('h3','',p.name),node('p','record-meta',p.status+' · '+p.hash.slice(0,16)),button('내용 검토',async()=>{const r=await api('mesh-preview',{hash:p.hash});review('탐색 절차 검토',JSON.stringify(r.document,null,2)+'\n서명은 발신자를 확인할 뿐 내용의 정확성을 보장하지 않습니다. 후보 등록 후 기억과 경로에서 별도 검증하세요.',()=>action('mesh-adopt',{hash:p.hash}));}));h.append(c);}});
 changed('mesh-publish',[data.routes,m.published],()=>{const h=$('mesh-publish');h.replaceChildren();const routes=data.routes.filter(r=>r.status==='active');if(!routes.length)empty(h,'기억과 경로에서 검증한 절차가 여기에 나타납니다.');for(const r of routes){const c=node('article','record');c.append(node('h3','',r.name),node('p','',r.problem),button('공유 피드에 추가',()=>review('이 절차를 공유',JSON.stringify(Object.fromEntries(['problem','locator','strategy','verification','fallback','related'].map(k=>[k,r[k]])),null,2)+'\n피드 서버를 공개하면 이 내용은 다른 사람이 가져갈 수 있습니다. 비밀이나 개인 정보가 없는지 확인하세요.',()=>action('mesh-publish',{name:r.name,digest:r.digest}))));h.append(c);}});
}
$('peer-form').onsubmit=async e=>{e.preventDefault();try{await action('mesh-pair',{url:$('peer-url').value,public:$('peer-public').value.trim()});$('peer-url').value='';$('peer-public').value='';}catch{}};
window.addEventListener('cell-snapshot',e=>renderChat(e.detail));
